# Generated by Django 3.1.7 on 2021-04-05 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='is_restricted',
            field=models.BooleanField(default=False),
        ),
    ]
