# Generated by Django 3.1.7 on 2021-04-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userinfo_is_restricted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='phone',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
