# Generated by Django 3.1.7 on 2021-04-05 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenreField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_type', models.CharField(max_length=56)),
            ],
        ),
        migrations.CreateModel(
            name='SectorField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=56)),
                ('genre', models.ManyToManyField(related_name='sec', to='connect.GenreField')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateTimeField()),
                ('subject', models.CharField(max_length=128)),
                ('content', models.TextField()),
                ('requester', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='req', to=settings.AUTH_USER_MODEL)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reqsec', to='connect.sectorfield')),
            ],
        ),
    ]
