# Generated by Django 3.1.7 on 2021-04-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='genre',
            field=models.CharField(blank=True, max_length=56, null=True),
        ),
    ]
