# Generated by Django 3.1.7 on 2021-04-07 19:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0003_request_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectorfield',
            name='image',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
