# Generated by Django 3.1.7 on 2021-04-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0004_sectorfield_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genrefield',
            name='genre_type',
            field=models.CharField(max_length=56, unique=True),
        ),
        migrations.AlterField(
            model_name='sectorfield',
            name='name',
            field=models.CharField(max_length=56, unique=True),
        ),
    ]
