# Generated by Django 3.1.7 on 2021-04-07 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0005_auto_20210408_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='is_first_year_req',
            field=models.BooleanField(default=False),
        ),
    ]
