# Generated by Django 3.1.7 on 2021-04-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0006_request_is_first_year_req'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='same_gender',
            field=models.BooleanField(default=False),
        ),
    ]
