# Generated by Django 3.1.7 on 2021-04-10 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0007_request_same_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='same_gender',
            new_name='match_with_same_gender',
        ),
    ]
