# Generated by Django 3.1.7 on 2021-04-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0008_auto_20210410_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='pending',
            field=models.BooleanField(default=True),
        ),
    ]
