# Generated by Django 3.1.7 on 2021-04-11 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0009_auto_20210411_2142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['-created_at']},
        ),
    ]
