# Generated by Django 3.1.7 on 2021-04-15 19:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('connect', '0012_finalmatchingrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalmatchingrequest',
            name='final_req_users',
            field=models.ManyToManyField(related_name='finalmatchuser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='initialmatchingrequest',
            name='req_users',
            field=models.ManyToManyField(related_name='initialmatchuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
